development:
  adapter: mysql
  database: scavenge_development

test: &TEST
  adapter: mysql
  database: scavenge_test

production:
  adapter: mysql
  database: scavenge_prod
  username: scavenge_prod_user
  password: not-the-real-one
  host: db.ndwebgroup.railsmachina.com